# Generated by Django 3.2.8 on 2022-11-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='email',
            new_name='login',
        ),
    ]
