# Generated by Django 3.2.8 on 2022-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221104_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cash',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
