# Generated by Django 3.2.8 on 2022-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='health',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
