# Generated by Django 3.2.8 on 2022-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_game_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='monsters',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
