# Generated by Django 3.2.8 on 2022-11-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_game_monsters'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cash',
            field=models.CharField(default=100, max_length=32),
        ),
    ]
