# Generated by Django 3.2.8 on 2022-11-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_game_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
